# Generated by Django 5.0.2 on 2024-05-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naira_deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
    ]
