# Generated by Django 5.0.2 on 2024-05-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_account_bank_name_naira_deposit_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFA_deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=205, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Euro_deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=205, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='USD_deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=205, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
    ]
