# Generated by Django 5.0.2 on 2024-07-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_amazon_giftcard_rate_naira_rate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Giftcard_Rate',
            new_name='Giftcard',
        ),
        migrations.RemoveConstraint(
            model_name='giftcard',
            name='card',
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.UniqueConstraint(fields=('card_type',), name='card_type'),
        ),
    ]
