# Generated by Django 5.0.2 on 2024-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_giftcard_buyrate_giftcard_buyrate_sell_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(blank=True, max_length=30, null=True)),
                ('naira_rate', models.FloatField(default=1500, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='crypto',
            constraint=models.UniqueConstraint(fields=('coin_type',), name='coin_type'),
        ),
    ]
