# Generated by Django 5.0.2 on 2024-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_crypto_crypto_coin_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_coin_type', models.CharField(blank=True, max_length=30, null=True)),
                ('naira_rate', models.FloatField(default=1500, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sellcrypto',
            constraint=models.UniqueConstraint(fields=('sell_coin_type',), name='sell_coin_type'),
        ),
    ]
