# Generated by Django 5.0.2 on 2024-08-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sellcrypto_sellcrypto_sell_coin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, default='Not Found', max_length=64, null=True),
        ),
    ]
