# Generated by Django 5.0.2 on 2024-03-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cryptodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, max_length=64, null=True)),
                ('crypto_to_purchase', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(default=0, null=True)),
                ('recieving_wallet_address', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
    ]
