# Generated by Django 5.0.2 on 2024-05-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_naira_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='naira_deposit',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='naira_deposit',
            name='account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='naira_deposit',
            name='bank_name',
            field=models.CharField(blank=True, max_length=205, null=True),
        ),
    ]
