# Generated by Django 5.0.2 on 2024-05-18 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cfa_deposit_euro_deposit_usd_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maximum_withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_withdrawal', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Minimum_withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_withdrawal', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_type', models.CharField(default='Withdrawal', max_length=64, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('bankaccount_number', models.CharField(max_length=100, null=True)),
                ('amount', models.FloatField(default=0, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
    ]
