# Generated by Django 5.0.2 on 2024-07-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_maximum_withdrawal_minimum_withdrawal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giftcard_Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon', models.FloatField(default=500, null=True)),
                ('apple', models.FloatField(default=500, null=True)),
                ('google_play', models.FloatField(default=500, null=True)),
                ('play_station', models.FloatField(default=500, null=True)),
                ('visa', models.FloatField(default=500, null=True)),
                ('walmart', models.FloatField(default=500, null=True)),
                ('xbox', models.FloatField(default=500, null=True)),
            ],
        ),
    ]
