# Generated by Django 5.0.2 on 2024-07-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_giftcard_rates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Giftcard_Rates',
            new_name='Giftcard_Rate',
        ),
    ]
