# Generated by Django 5.0.2 on 2024-07-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_giftcard_rates_giftcard_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard_rate',
            old_name='amazon',
            new_name='naira_rate',
        ),
        migrations.RemoveField(
            model_name='giftcard_rate',
            name='apple',
        ),
        migrations.RemoveField(
            model_name='giftcard_rate',
            name='google_play',
        ),
        migrations.RemoveField(
            model_name='giftcard_rate',
            name='play_station',
        ),
        migrations.RemoveField(
            model_name='giftcard_rate',
            name='visa',
        ),
        migrations.RemoveField(
            model_name='giftcard_rate',
            name='walmart',
        ),
        migrations.RemoveField(
            model_name='giftcard_rate',
            name='xbox',
        ),
        migrations.AddField(
            model_name='giftcard_rate',
            name='card_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='giftcard_rate',
            constraint=models.UniqueConstraint(fields=('card_type',), name='card'),
        ),
    ]
