# Generated by Django 5.0.2 on 2024-07-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_giftcard_rate_giftcard_remove_giftcard_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giftcard_buyrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_card_type', models.CharField(blank=True, max_length=30, null=True)),
                ('naira_rate', models.FloatField(default=500, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='giftcard_buyrate',
            constraint=models.UniqueConstraint(fields=('sell_card_type',), name='sell_card_type'),
        ),
    ]
