# Generated by Django 5.0.2 on 2024-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(blank=True, choices=[('Airtime', 'Airtime'), ('Data', 'Data'), ('CryptoPurchase', 'CryptoPurchase'), ('CryptoSale', 'CryptoSale'), ('Electricity', 'Electricity'), ('BetTopup', 'BetTopup'), ('GiftcardPurchase', 'GiftcardPurchase'), ('GiftcardSale', 'GiftcardSale'), ('CableTv', 'CableTv')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('incomplete', 'incomplete'), ('pending', 'pending')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, default='Not Found', max_length=64, null=True),
        ),
    ]
